### ISSUE TITLE
Crash when started game and entering controls tab

### ISSUE THREAD

**Issue by Njet75** [TeamMonumental/FissionWarfare#2]
Awsome mod
Get this crash in controls tab when in a game
Dont crash if no world loaded
Hope this helps
/Michael
--- Minecraft Crash Report ----
// Why is it breaking :(

Time: 7/3/16 4:38 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.client.gui.GuiListExtended.func_148181_b(SourceFile:53)
    at net.minecraft.client.gui.GuiControls.func_146286_b(SourceFile:81)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:270)
    at net.minecraft.client.gui.GuiControls.func_73863_a(SourceFile:107)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by Calemi** [comment]
Thanks for the report. We also encountered this when testing. It will be
fixed in the next update.

—Calemi
